spring:
  application:
    name: stock-web-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://steve-mysql0.mysql.rds.aliyuncs.com:3306/iblog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root_steve1
    password: root123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 30
      min-idle: 5
      initial-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: 8402
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
eureka:
  instance:
    hostname: localhost
  client:
    eureka-server-port: 8400
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    register-with-eureka: true
    fetch-registry: true